# Build documentation
name: Documentation Build

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs_build:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.8

      - name: Style Check
        run: |
          pip install -r requirements_style.txt --disable-pip-version-check
          make

      - name: Build Documentation
        run: |
          pip install -r requirements_docs.txt
          make -C doc html
          touch doc/build/html/.nojekyll

      - name: Upload Documentation
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Documentation
          path: doc/build/html
          retention-days: 7

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        if: startsWith(github.event.ref, 'refs/tags')
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/build/html
          CLEAN: true
          FORCE: false
